# Generated by Django 6.0.6 on 2026-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='applications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='external_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
