# Generated by Django 6.0.6 on 2026-06-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_ai_summary_article_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
